### PR TITLE
Changed WiFi connection detection to Event Based Listener

### LINKED ISSUE #24: Possible memory leak when service is running
Steps to reproduce:

- Open up client, and make sure service is running

- Make sure server is not running. If it is, close it down to ensure no processing on the client is happening. 

- Open the Android monitor and select the crowd-ml:datasend process. View the allocated memory continuously increasing in the performance profiler. 

This may be due to the wifi listener, because that is the only running thread in the :datasend process.

### PR DESCRIPTION
**Pull request by 3ygun**
# What?

Following the https://stackoverflow.com/questions/1783117/network-listener-android and https://developer.android.com/reference/android/net/ConnectivityManager.html I changed from the custom WiFi ready code to an event listener one. Appears to work tested turning on and off the WiFi on my phone and the app didn't crash and was able to resume calculations. Also seems to resolve #24

# Parts

**NOTE**: DO NOT MERGE UNTIL THE FOLLOWING ARE COMPLETE

- [x] Remove old wifi code
- [x] Refractor out new code?

# Fixes

- [x] #25 
- [x] #24
- [x] #15  -- How should I test this?

### CODE REVIEW

**Comment by tylermzeller** [comment]
Confirmed memory leak fix?

**Comment by 3ygun** [comment]
@tylermzeller I removed the WifiHandler thread also. Could you check through the changes and see if they work on your end.

# My Concerns

- Didn't know if I tested a full disconnect/onDestroy of the app and made sure it could recover
- I didn't add any destroy `broadcastReciever` code [see](https://stackoverflow.com/questions/30029177/android-how-to-destroy-a-broadcastreceiver) if we want to add it

File: client/android/Crowd-ML/app/src/main/java/osu/crowd_ml/BackgroundDataSend.java [hunk 1]
```diff
@@ -296,14 +278,14 @@ private void removeFirebaseListeners(){
 
     @Override public void onDestroy() {
 
+        Log.d("onDestroy", "Unregister Wifi receiver.");
+        // Step 1. End the wifi receiver.
+        unregisterReceiver(receiver);
```
Comment (tylermzeller) [inline client/android/Crowd-ML/app/src/main/java/osu/crowd_ml/BackgroundDataSend.java]: Stop the work thread before disabling wifi. Since the work thread will be interrupted by a wifi change, it's better practice to end the dependent component first.

File: client/android/Crowd-ML/app/src/main/java/osu/crowd_ml/BackgroundDataSend.java [hunk 2]
```diff
@@ -191,49 +176,46 @@ public void handleMessage(Message msg){
...
+                return cm.getActiveNetworkInfo().isConnectedOrConnecting();
+            } else {
+                return false;
+            }
+        } catch (Exception e) {
+            return false;
+        }
+    }
+
+    private void handleWifiChange() {
```
Comment (tylermzeller) [inline client/android/Crowd-ML/app/src/main/java/osu/crowd_ml/BackgroundDataSend.java]: I like this event based method. Cleans up the codebase a lot.

File: client/android/Crowd-ML/app/src/main/java/osu/crowd_ml/BackgroundDataSend.java (hunk 1 above)
Comment (3ygun) [inline client/android/Crowd-ML/app/src/main/java/osu/crowd_ml/BackgroundDataSend.java]: Changed on https://github.com/jihunhamm/Crowd-ML/pull/26/commits/a30b768118eb77b46c16acba409435c768e73b5e placed as step 3 below all wifi dependent things
